# Generated by Django 5.0.6 on 2024-06-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
